### ISSUE TITLE
Can Lux Subscribers support re-subscribing if postal is nuked.

### ISSUE THREAD

**Issue by ifandelse** [LeanKit-Labs/lux.js#36]

**Comment by dcneiner** [comment]
Is this still something we want to look into adding? It seems like our `dispose` and `createSubscribers` methods on dispatcher might have removed the pain behind this request. Thoughts @rniemeyer or @ifandelse?

**Comment by rniemeyer** [comment]
I don't see this as being a big problem any longer. I think that it originated from some pain in testing, but doing proper cleanup of the lux objects was the better choice than resetting postal.

**Comment by ifandelse** [comment]
I'm good with closing this if the original pain points have been resolved elsewhere
