### ISSUE TITLE
Consider moving postal.js to peer dependency

### ISSUE THREAD

**Issue by dcneiner** [LeanKit-Labs/lux.js#55]
Since multiple versions of postal can potentially be an issue, it seems like this might be a good candidate to list as a peer dep vs hard dependency. 

However, perhaps something like webpack-dedupe would solve the issues we had today from differing versions of postal and lux.js.

@ifandelse We forgot to update the version range on postal during the tagging of the latest version, so that is another thing that might help.

**Comment by ifandelse** [comment]
@dcneiner @rniemeyer @arobson @brianedgerton  At the very least we need to allow a range of supported postal versions - and I'm open to moving to a peer dependency. After all, react is already one. Any thoughts on pros vs cons? Peer deps seem to be a "love 'em or hate 'em" topic....
